### ISSUE TITLE
sfLIU - Implement React Router

### ISSUE THREAD

**Issue by zhg-kj** [edwardhuahan/tli-speakfluid#78]
Implement React Router for page routing in the frontend.

**Comment by edwardhuahan** [comment]
LOL react router is kinda annoying right now because they changed everything so all the documentation online is messed up. **Use VERSION 5**

**Comment by zhg-kj** [comment]
> LOL react router is kinda annoying right now because they changed everything so all the documentation online is messed up. **Use VERSION 5**

I got it working with v6 no worries.
